# Gemfile to help setting up the initial development environment
source 'https://rubygems.org'

gem 'appium_console'
gem 'appium_lib'
gem 'cucumber'
gem 'firebase'
gem 'google-api-client'
gem 'nokogiri'
gem 'parallel_tests'
gem 'pry'
gem 'report_builder'
gem 'rest-client'
# gem 'rmagick', '2.16.0'
gem 'rspec'
gem 'rtesseract'
gem 'rubocop'
